package outboundproxy

import "testing"

func TestParseSystemProxy(t *testing.T) {
	result := parseSystemProxy(`<dictionary> {
  HTTPEnable : 1
  HTTPPort : 7890
  HTTPProxy : 127.0.0.1
  HTTPSEnable : 1
  HTTPSPort : 7890
  HTTPSProxy : 127.0.0.1
}`)
	if result.HTTPProxy != "http://127.0.0.1:7890" || result.HTTPSProxy != "http://127.0.0.1:7890" {
		t.Fatalf("unexpected system proxy: %#v", result)
	}
}

func TestParseSystemProxyFallsBackToSocks(t *testing.T) {
	result := parseSystemProxy(`<dictionary> {
  HTTPEnable : 0
  HTTPSEnable : 0
  SOCKSEnable : 1
  SOCKSPort : 7891
  SOCKSProxy : 127.0.0.1
}`)
	if result.AllProxy != "socks5://127.0.0.1:7891" {
		t.Fatalf("unexpected SOCKS proxy: %#v", result)
	}
}

func TestParseClashPortsUsesTopLevelValues(t *testing.T) {
	ports := parseClashPorts(`# Generated by Clash Verge
mixed-port: 7890
port: 7897 # HTTP fallback
profile:
  port: 9999
socks-port: 7891
`)
	if ports["mixed-port"] != 7890 || ports["port"] != 7897 || ports["socks-port"] != 7891 {
		t.Fatalf("unexpected Clash ports: %#v", ports)
	}
}

func TestProxyURLRejectsInvalidPort(t *testing.T) {
	if got := proxyURL("http", "127.0.0.1", "70000"); got != "" {
		t.Fatalf("expected invalid port to be rejected, got %q", got)
	}
}

func TestResultURLPreference(t *testing.T) {
	result := Result{HTTPProxy: "http://http:1", HTTPSProxy: "http://https:2", AllProxy: "socks5://all:3"}
	if got := result.URL(); got != result.HTTPSProxy {
		t.Fatalf("URL() = %q, want %q", got, result.HTTPSProxy)
	}
}
